/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Objects;

namespace ppSoft_MySql
{
	public partial class frmdepartment : Form
	{
		private Model1Entities ctx;
		
		public frmdepartment()
		{
			InitializeComponent();
		}
		
		private void frmdepartment_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ObjectResult<department> _entities = ctx.department.Execute(MergeOption.AppendOnly);
			departmentBindingSource.DataSource = _entities;
			this.departmentIDTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.departmentBindingSource, "departmentID", true ));
			this.departmentTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.departmentBindingSource, "department1", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			departmentBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmdepartment_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void departmentIDTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( departmentIDTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( departmentIDTextBox, "The field departmentID is required" ); 
			}
			int v;
			string s = departmentIDTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( departmentIDTextBox, "The field departmentID must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( departmentIDTextBox, "" ); } 
		}
		
		private void departmentTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( departmentTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( departmentTextBox, "The field department is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( departmentTextBox, "" ); } 
		}
		
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			departmentBindingSource.AddNew();
		}
	}
}
