/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

namespace ppSoft_MySql
{
	partial class frmemployee
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}
		
		#region Windows Form Designer generated code
		
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmemployee));
			this.bindingNavigator1 = new System.Windows.Forms.BindingNavigator(this.components);
			this.bindingNavigatorAddNewItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorCountItem = new System.Windows.Forms.ToolStripLabel();
			this.bindingNavigatorDeleteItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveFirstItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMovePreviousItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorPositionItem = new System.Windows.Forms.ToolStripTextBox();
			this.bindingNavigatorSeparator1 = new System.Windows.Forms.ToolStripSeparator();
			this.bindingNavigatorMoveNextItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorMoveLastItem = new System.Windows.Forms.ToolStripButton();
			this.bindingNavigatorSeparator2 = new System.Windows.Forms.ToolStripSeparator();
			this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
			this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
			
			this.Panel1 = new System.Windows.Forms.Panel();
			
			this.employeeBindingSource = new System.Windows.Forms.BindingSource(this.components);
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel4 = new System.Windows.Forms.Panel();
			this.panel5 = new System.Windows.Forms.Panel();
			this.panel6 = new System.Windows.Forms.Panel();
			
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
			this.bindingNavigator1.SuspendLayout();
			this.panel3.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).BeginInit();
			
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bindingNavigator1
			// 
			this.bindingNavigator1.AddNewItem = null;
			this.bindingNavigator1.CountItem = this.bindingNavigatorCountItem;
			this.bindingNavigator1.DeleteItem = this.bindingNavigatorDeleteItem;
			this.bindingNavigator1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
			this.bindingNavigatorMoveFirstItem,
			this.bindingNavigatorMovePreviousItem,
			this.bindingNavigatorSeparator,
			this.bindingNavigatorPositionItem,
			this.bindingNavigatorCountItem,
			this.bindingNavigatorSeparator1,
			this.bindingNavigatorMoveNextItem,
			this.bindingNavigatorMoveLastItem,
			this.bindingNavigatorSeparator2,
			this.bindingNavigatorAddNewItem,
			this.bindingNavigatorDeleteItem,
			this.toolStripButton1});
			this.bindingNavigator1.Location = new System.Drawing.Point(0, 0);
			this.bindingNavigator1.MoveFirstItem = this.bindingNavigatorMoveFirstItem;
			this.bindingNavigator1.MoveLastItem = this.bindingNavigatorMoveLastItem;
			this.bindingNavigator1.MoveNextItem = this.bindingNavigatorMoveNextItem;
			this.bindingNavigator1.MovePreviousItem = this.bindingNavigatorMovePreviousItem;
			this.bindingNavigator1.Name = "bindingNavigator1";
			this.bindingNavigator1.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
			this.bindingNavigator1.PositionItem = this.bindingNavigatorPositionItem;
			this.bindingNavigator1.Size = new System.Drawing.Size(360, 25);
			this.bindingNavigator1.TabIndex = 0;
			this.bindingNavigator1.Text = "bindingNavigator1";
			// 
			// bindingNavigatorAddNewItem
			// 
			this.bindingNavigatorAddNewItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorAddNewItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorAddNewItem.Image")));
			this.bindingNavigatorAddNewItem.Name = "bindingNavigatorAddNewItem";
			this.bindingNavigatorAddNewItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorAddNewItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorAddNewItem.Text = "Add new";
			this.bindingNavigatorAddNewItem.Click += new System.EventHandler(this.bindingNavigatorAddNewItem_Click);
			// 
			// bindingNavigatorCountItem
			// 
			this.bindingNavigatorCountItem.Name = "bindingNavigatorCountItem";
			this.bindingNavigatorCountItem.Size = new System.Drawing.Size(35, 22);
			this.bindingNavigatorCountItem.Text = "of {0}";
			this.bindingNavigatorCountItem.ToolTipText = "Total number of items";
			// 
			// bindingNavigatorDeleteItem
			// 
			this.bindingNavigatorDeleteItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorDeleteItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorDeleteItem.Image")));
			this.bindingNavigatorDeleteItem.Name = "bindingNavigatorDeleteItem";
			this.bindingNavigatorDeleteItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorDeleteItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorDeleteItem.Text = "Delete";
			// 
			// bindingNavigatorMoveFirstItem
			// 
			this.bindingNavigatorMoveFirstItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveFirstItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveFirstItem.Image")));
			this.bindingNavigatorMoveFirstItem.Name = "bindingNavigatorMoveFirstItem";
			this.bindingNavigatorMoveFirstItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveFirstItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveFirstItem.Text = "Move first";
			// 
			// bindingNavigatorMovePreviousItem
			// 
			this.bindingNavigatorMovePreviousItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMovePreviousItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMovePreviousItem.Image")));
			this.bindingNavigatorMovePreviousItem.Name = "bindingNavigatorMovePreviousItem";
			this.bindingNavigatorMovePreviousItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMovePreviousItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMovePreviousItem.Text = "Move previous";
			// 
			// bindingNavigatorSeparator
			// 
			this.bindingNavigatorSeparator.Name = "bindingNavigatorSeparator";
			this.bindingNavigatorSeparator.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorPositionItem
			// 
			this.bindingNavigatorPositionItem.AccessibleName = "Position";
			this.bindingNavigatorPositionItem.AutoSize = false;
			this.bindingNavigatorPositionItem.Name = "bindingNavigatorPositionItem";
			this.bindingNavigatorPositionItem.Size = new System.Drawing.Size(50, 23);
			this.bindingNavigatorPositionItem.Text = "0";
			this.bindingNavigatorPositionItem.ToolTipText = "Current position";
			// 
			// bindingNavigatorSeparator1
			// 
			this.bindingNavigatorSeparator1.Name = "bindingNavigatorSeparator1";
			this.bindingNavigatorSeparator1.Size = new System.Drawing.Size(6, 25);
			// 
			// bindingNavigatorMoveNextItem
			// 
			this.bindingNavigatorMoveNextItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveNextItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveNextItem.Image")));
			this.bindingNavigatorMoveNextItem.Name = "bindingNavigatorMoveNextItem";
			this.bindingNavigatorMoveNextItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveNextItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveNextItem.Text = "Move next";
			// 
			// bindingNavigatorMoveLastItem
			// 
			this.bindingNavigatorMoveLastItem.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.bindingNavigatorMoveLastItem.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorMoveLastItem.Image")));
			this.bindingNavigatorMoveLastItem.Name = "bindingNavigatorMoveLastItem";
			this.bindingNavigatorMoveLastItem.RightToLeftAutoMirrorImage = true;
			this.bindingNavigatorMoveLastItem.Size = new System.Drawing.Size(23, 22);
			this.bindingNavigatorMoveLastItem.Text = "Move last";
			// 
			// bindingNavigatorSeparator2
			// 
			this.bindingNavigatorSeparator2.Name = "bindingNavigatorSeparator2";
			this.bindingNavigatorSeparator2.Size = new System.Drawing.Size(6, 25);
			// 
			// toolStripButton1
			// 
			this.toolStripButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
			this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("bindingNavigatorSaveItem.Image")));
			this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
			this.toolStripButton1.Name = "toolStripButton1";
			this.toolStripButton1.Size = new System.Drawing.Size(23, 22);
			this.toolStripButton1.Text = "Save";
			this.toolStripButton1.Click += new System.EventHandler(this.Save_Click);
			// 
			// errorProvider1
			// 
			this.errorProvider1.ContainerControl = this;
			//
			// Panel1
			//
			this.Panel1.AutoScroll = true;
			this.Panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new System.Drawing.Point(0, 25);
			this.Panel1.Margin = new System.Windows.Forms.Padding(10, 3, 10, 3);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(656, 183);
			this.Panel1.TabIndex = 1;
			this.Panel1.AutoSize = true;
			
			this.bindingNavigator1.BindingSource = this.employeeBindingSource;
			//
			// employeeIDLabel
			//
			this.employeeIDLabel = new System.Windows.Forms.Label();
			this.employeeIDLabel.AutoSize = true;
			this.employeeIDLabel.Location = new System.Drawing.Point( 67, 50 );
			this.employeeIDLabel.Name = "employeeIDLabel";
			this.employeeIDLabel.Size = new System.Drawing.Size( 63, 13 );
			this.employeeIDLabel.TabIndex = 1;
			this.employeeIDLabel.Text = "employeeID";
			this.Panel1.Controls.Add( this.employeeIDLabel );
			//
			// employeeIDTextBox
			//
			this.employeeIDTextBox = new System.Windows.Forms.TextBox();
			this.employeeIDTextBox.Location = new System.Drawing.Point( 140, 50 );
			this.employeeIDTextBox.Name = "employeeIDTextBox";
			this.employeeIDTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.employeeIDTextBox.TabIndex = 2;
			this.employeeIDTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.employeeIDTextBox_Validating );
			this.Panel1.Controls.Add( this.employeeIDTextBox);
			//
			// passwordLabel
			//
			this.passwordLabel = new System.Windows.Forms.Label();
			this.passwordLabel.AutoSize = true;
			this.passwordLabel.Location = new System.Drawing.Point( 78, 76 );
			this.passwordLabel.Name = "passwordLabel";
			this.passwordLabel.Size = new System.Drawing.Size( 52, 13 );
			this.passwordLabel.TabIndex = 3;
			this.passwordLabel.Text = "password";
			this.Panel1.Controls.Add( this.passwordLabel );
			//
			// passwordTextBox
			//
			this.passwordTextBox = new System.Windows.Forms.TextBox();
			this.passwordTextBox.Location = new System.Drawing.Point( 140, 76 );
			this.passwordTextBox.Name = "passwordTextBox";
			this.passwordTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.passwordTextBox.TabIndex = 4;
			this.passwordTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.passwordTextBox_Validating );
			this.Panel1.Controls.Add( this.passwordTextBox);
			//
			// firstNameLabel
			//
			this.firstNameLabel = new System.Windows.Forms.Label();
			this.firstNameLabel.AutoSize = true;
			this.firstNameLabel.Location = new System.Drawing.Point( 79, 102 );
			this.firstNameLabel.Name = "firstNameLabel";
			this.firstNameLabel.Size = new System.Drawing.Size( 51, 13 );
			this.firstNameLabel.TabIndex = 5;
			this.firstNameLabel.Text = "firstName";
			this.Panel1.Controls.Add( this.firstNameLabel );
			//
			// firstNameTextBox
			//
			this.firstNameTextBox = new System.Windows.Forms.TextBox();
			this.firstNameTextBox.Location = new System.Drawing.Point( 140, 102 );
			this.firstNameTextBox.Name = "firstNameTextBox";
			this.firstNameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.firstNameTextBox.TabIndex = 6;
			this.firstNameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.firstNameTextBox_Validating );
			this.Panel1.Controls.Add( this.firstNameTextBox);
			//
			// lastNameLabel
			//
			this.lastNameLabel = new System.Windows.Forms.Label();
			this.lastNameLabel.AutoSize = true;
			this.lastNameLabel.Location = new System.Drawing.Point( 79, 128 );
			this.lastNameLabel.Name = "lastNameLabel";
			this.lastNameLabel.Size = new System.Drawing.Size( 51, 13 );
			this.lastNameLabel.TabIndex = 7;
			this.lastNameLabel.Text = "lastName";
			this.Panel1.Controls.Add( this.lastNameLabel );
			//
			// lastNameTextBox
			//
			this.lastNameTextBox = new System.Windows.Forms.TextBox();
			this.lastNameTextBox.Location = new System.Drawing.Point( 140, 128 );
			this.lastNameTextBox.Name = "lastNameTextBox";
			this.lastNameTextBox.Size = new System.Drawing.Size( 100, 20 );
			this.lastNameTextBox.TabIndex = 8;
			this.lastNameTextBox.Validating += new System.ComponentModel.CancelEventHandler( this.lastNameTextBox_Validating );
			this.Panel1.Controls.Add( this.lastNameTextBox);
			//
			// access_levelIDLabel
			//
			this.access_levelIDLabel = new System.Windows.Forms.Label();
			this.access_levelIDLabel.AutoSize = true;
			this.access_levelIDLabel.Location = new System.Drawing.Point( 50, 154 );
			this.access_levelIDLabel.Name = "access_levelIDLabel";
			this.access_levelIDLabel.Size = new System.Drawing.Size( 80, 13 );
			this.access_levelIDLabel.TabIndex = 9;
			this.access_levelIDLabel.Text = "access_levelID";
			this.Panel1.Controls.Add( this.access_levelIDLabel );
			this.access_levelID_comboBox = new System.Windows.Forms.ComboBox();
			this.access_levelID_comboBox.Location = new System.Drawing.Point( 140, 154 );
			this.access_levelID_comboBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Append;
			this.access_levelID_comboBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
			this.access_levelID_comboBox.FormattingEnabled = true;
			this.access_levelID_comboBox.Name = "access_levelID_comboBox";
			this.access_levelID_comboBox.Size = new System.Drawing.Size(206, 21);
			this.access_levelID_comboBox.TabIndex = 10;
			this.access_levelID_comboBox.Validating += new System.ComponentModel.CancelEventHandler( this.access_levelID_comboBox_Validating );
			this.Panel1.Controls.Add( this.access_levelID_comboBox );
			//
			// sunStartLabel
			//
			this.sunStartLabel = new System.Windows.Forms.Label();
			this.sunStartLabel.AutoSize = true;
			this.sunStartLabel.Location = new System.Drawing.Point( 84, 180 );
			this.sunStartLabel.Name = "sunStartLabel";
			this.sunStartLabel.Size = new System.Drawing.Size( 46, 13 );
			this.sunStartLabel.TabIndex = 11;
			this.sunStartLabel.Text = "sunStart";
			this.Panel1.Controls.Add( this.sunStartLabel );
			//
			// sunStart_dateTimePicker
			//
			this.sunStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.sunStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.sunStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.sunStart_dateTimePicker.Location = new System.Drawing.Point(140, 180);
			this.sunStart_dateTimePicker.Name = "sunStart_dateTimePicker";
			this.sunStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.sunStart_dateTimePicker.TabIndex = 12;
			this.sunStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.sunStart_dateTimePicker );
			//
			// sunEndLabel
			//
			this.sunEndLabel = new System.Windows.Forms.Label();
			this.sunEndLabel.AutoSize = true;
			this.sunEndLabel.Location = new System.Drawing.Point( 87, 206 );
			this.sunEndLabel.Name = "sunEndLabel";
			this.sunEndLabel.Size = new System.Drawing.Size( 43, 13 );
			this.sunEndLabel.TabIndex = 13;
			this.sunEndLabel.Text = "sunEnd";
			this.Panel1.Controls.Add( this.sunEndLabel );
			//
			// sunEnd_dateTimePicker
			//
			this.sunEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.sunEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.sunEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.sunEnd_dateTimePicker.Location = new System.Drawing.Point(140, 206);
			this.sunEnd_dateTimePicker.Name = "sunEnd_dateTimePicker";
			this.sunEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.sunEnd_dateTimePicker.TabIndex = 14;
			this.sunEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.sunEnd_dateTimePicker );
			//
			// monStartLabel
			//
			this.monStartLabel = new System.Windows.Forms.Label();
			this.monStartLabel.AutoSize = true;
			this.monStartLabel.Location = new System.Drawing.Point( 81, 232 );
			this.monStartLabel.Name = "monStartLabel";
			this.monStartLabel.Size = new System.Drawing.Size( 49, 13 );
			this.monStartLabel.TabIndex = 15;
			this.monStartLabel.Text = "monStart";
			this.Panel1.Controls.Add( this.monStartLabel );
			//
			// monStart_dateTimePicker
			//
			this.monStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.monStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.monStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.monStart_dateTimePicker.Location = new System.Drawing.Point(140, 232);
			this.monStart_dateTimePicker.Name = "monStart_dateTimePicker";
			this.monStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.monStart_dateTimePicker.TabIndex = 16;
			this.monStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.monStart_dateTimePicker );
			//
			// monEndLabel
			//
			this.monEndLabel = new System.Windows.Forms.Label();
			this.monEndLabel.AutoSize = true;
			this.monEndLabel.Location = new System.Drawing.Point( 84, 258 );
			this.monEndLabel.Name = "monEndLabel";
			this.monEndLabel.Size = new System.Drawing.Size( 46, 13 );
			this.monEndLabel.TabIndex = 17;
			this.monEndLabel.Text = "monEnd";
			this.Panel1.Controls.Add( this.monEndLabel );
			//
			// monEnd_dateTimePicker
			//
			this.monEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.monEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.monEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.monEnd_dateTimePicker.Location = new System.Drawing.Point(140, 258);
			this.monEnd_dateTimePicker.Name = "monEnd_dateTimePicker";
			this.monEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.monEnd_dateTimePicker.TabIndex = 18;
			this.monEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.monEnd_dateTimePicker );
			//
			// tueStartLabel
			//
			this.tueStartLabel = new System.Windows.Forms.Label();
			this.tueStartLabel.AutoSize = true;
			this.tueStartLabel.Location = new System.Drawing.Point( 386, 50 );
			this.tueStartLabel.Name = "tueStartLabel";
			this.tueStartLabel.Size = new System.Drawing.Size( 44, 13 );
			this.tueStartLabel.TabIndex = 19;
			this.tueStartLabel.Text = "tueStart";
			this.Panel1.Controls.Add( this.tueStartLabel );
			//
			// tueStart_dateTimePicker
			//
			this.tueStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.tueStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.tueStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.tueStart_dateTimePicker.Location = new System.Drawing.Point(440, 50);
			this.tueStart_dateTimePicker.Name = "tueStart_dateTimePicker";
			this.tueStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.tueStart_dateTimePicker.TabIndex = 20;
			this.tueStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.tueStart_dateTimePicker );
			//
			// tueEndLabel
			//
			this.tueEndLabel = new System.Windows.Forms.Label();
			this.tueEndLabel.AutoSize = true;
			this.tueEndLabel.Location = new System.Drawing.Point( 389, 76 );
			this.tueEndLabel.Name = "tueEndLabel";
			this.tueEndLabel.Size = new System.Drawing.Size( 41, 13 );
			this.tueEndLabel.TabIndex = 21;
			this.tueEndLabel.Text = "tueEnd";
			this.Panel1.Controls.Add( this.tueEndLabel );
			//
			// tueEnd_dateTimePicker
			//
			this.tueEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.tueEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.tueEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.tueEnd_dateTimePicker.Location = new System.Drawing.Point(440, 76);
			this.tueEnd_dateTimePicker.Name = "tueEnd_dateTimePicker";
			this.tueEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.tueEnd_dateTimePicker.TabIndex = 22;
			this.tueEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.tueEnd_dateTimePicker );
			//
			// wedStartLabel
			//
			this.wedStartLabel = new System.Windows.Forms.Label();
			this.wedStartLabel.AutoSize = true;
			this.wedStartLabel.Location = new System.Drawing.Point( 381, 102 );
			this.wedStartLabel.Name = "wedStartLabel";
			this.wedStartLabel.Size = new System.Drawing.Size( 49, 13 );
			this.wedStartLabel.TabIndex = 23;
			this.wedStartLabel.Text = "wedStart";
			this.Panel1.Controls.Add( this.wedStartLabel );
			//
			// wedStart_dateTimePicker
			//
			this.wedStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.wedStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.wedStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.wedStart_dateTimePicker.Location = new System.Drawing.Point(440, 102);
			this.wedStart_dateTimePicker.Name = "wedStart_dateTimePicker";
			this.wedStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.wedStart_dateTimePicker.TabIndex = 24;
			this.wedStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.wedStart_dateTimePicker );
			//
			// wedEndLabel
			//
			this.wedEndLabel = new System.Windows.Forms.Label();
			this.wedEndLabel.AutoSize = true;
			this.wedEndLabel.Location = new System.Drawing.Point( 384, 128 );
			this.wedEndLabel.Name = "wedEndLabel";
			this.wedEndLabel.Size = new System.Drawing.Size( 46, 13 );
			this.wedEndLabel.TabIndex = 25;
			this.wedEndLabel.Text = "wedEnd";
			this.Panel1.Controls.Add( this.wedEndLabel );
			//
			// wedEnd_dateTimePicker
			//
			this.wedEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.wedEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.wedEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.wedEnd_dateTimePicker.Location = new System.Drawing.Point(440, 128);
			this.wedEnd_dateTimePicker.Name = "wedEnd_dateTimePicker";
			this.wedEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.wedEnd_dateTimePicker.TabIndex = 26;
			this.wedEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.wedEnd_dateTimePicker );
			//
			// thuStartLabel
			//
			this.thuStartLabel = new System.Windows.Forms.Label();
			this.thuStartLabel.AutoSize = true;
			this.thuStartLabel.Location = new System.Drawing.Point( 386, 154 );
			this.thuStartLabel.Name = "thuStartLabel";
			this.thuStartLabel.Size = new System.Drawing.Size( 44, 13 );
			this.thuStartLabel.TabIndex = 27;
			this.thuStartLabel.Text = "thuStart";
			this.Panel1.Controls.Add( this.thuStartLabel );
			//
			// thuStart_dateTimePicker
			//
			this.thuStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.thuStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.thuStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.thuStart_dateTimePicker.Location = new System.Drawing.Point(440, 154);
			this.thuStart_dateTimePicker.Name = "thuStart_dateTimePicker";
			this.thuStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.thuStart_dateTimePicker.TabIndex = 28;
			this.thuStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.thuStart_dateTimePicker );
			//
			// thuEndLabel
			//
			this.thuEndLabel = new System.Windows.Forms.Label();
			this.thuEndLabel.AutoSize = true;
			this.thuEndLabel.Location = new System.Drawing.Point( 389, 180 );
			this.thuEndLabel.Name = "thuEndLabel";
			this.thuEndLabel.Size = new System.Drawing.Size( 41, 13 );
			this.thuEndLabel.TabIndex = 29;
			this.thuEndLabel.Text = "thuEnd";
			this.Panel1.Controls.Add( this.thuEndLabel );
			//
			// thuEnd_dateTimePicker
			//
			this.thuEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.thuEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.thuEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.thuEnd_dateTimePicker.Location = new System.Drawing.Point(440, 180);
			this.thuEnd_dateTimePicker.Name = "thuEnd_dateTimePicker";
			this.thuEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.thuEnd_dateTimePicker.TabIndex = 30;
			this.thuEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.thuEnd_dateTimePicker );
			//
			// friStartLabel
			//
			this.friStartLabel = new System.Windows.Forms.Label();
			this.friStartLabel.AutoSize = true;
			this.friStartLabel.Location = new System.Drawing.Point( 393, 206 );
			this.friStartLabel.Name = "friStartLabel";
			this.friStartLabel.Size = new System.Drawing.Size( 37, 13 );
			this.friStartLabel.TabIndex = 31;
			this.friStartLabel.Text = "friStart";
			this.Panel1.Controls.Add( this.friStartLabel );
			//
			// friStart_dateTimePicker
			//
			this.friStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.friStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.friStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.friStart_dateTimePicker.Location = new System.Drawing.Point(440, 206);
			this.friStart_dateTimePicker.Name = "friStart_dateTimePicker";
			this.friStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.friStart_dateTimePicker.TabIndex = 32;
			this.friStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.friStart_dateTimePicker );
			//
			// friEndLabel
			//
			this.friEndLabel = new System.Windows.Forms.Label();
			this.friEndLabel.AutoSize = true;
			this.friEndLabel.Location = new System.Drawing.Point( 396, 232 );
			this.friEndLabel.Name = "friEndLabel";
			this.friEndLabel.Size = new System.Drawing.Size( 34, 13 );
			this.friEndLabel.TabIndex = 33;
			this.friEndLabel.Text = "friEnd";
			this.Panel1.Controls.Add( this.friEndLabel );
			//
			// friEnd_dateTimePicker
			//
			this.friEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.friEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.friEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.friEnd_dateTimePicker.Location = new System.Drawing.Point(440, 232);
			this.friEnd_dateTimePicker.Name = "friEnd_dateTimePicker";
			this.friEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.friEnd_dateTimePicker.TabIndex = 34;
			this.friEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.friEnd_dateTimePicker );
			//
			// satStartLabel
			//
			this.satStartLabel = new System.Windows.Forms.Label();
			this.satStartLabel.AutoSize = true;
			this.satStartLabel.Location = new System.Drawing.Point( 387, 258 );
			this.satStartLabel.Name = "satStartLabel";
			this.satStartLabel.Size = new System.Drawing.Size( 43, 13 );
			this.satStartLabel.TabIndex = 35;
			this.satStartLabel.Text = "satStart";
			this.Panel1.Controls.Add( this.satStartLabel );
			//
			// satStart_dateTimePicker
			//
			this.satStart_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.satStart_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.satStart_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.satStart_dateTimePicker.Location = new System.Drawing.Point(440, 258);
			this.satStart_dateTimePicker.Name = "satStart_dateTimePicker";
			this.satStart_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.satStart_dateTimePicker.TabIndex = 36;
			this.satStart_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.satStart_dateTimePicker );
			//
			// satEndLabel
			//
			this.satEndLabel = new System.Windows.Forms.Label();
			this.satEndLabel.AutoSize = true;
			this.satEndLabel.Location = new System.Drawing.Point( 390, 284 );
			this.satEndLabel.Name = "satEndLabel";
			this.satEndLabel.Size = new System.Drawing.Size( 40, 13 );
			this.satEndLabel.TabIndex = 37;
			this.satEndLabel.Text = "satEnd";
			this.Panel1.Controls.Add( this.satEndLabel );
			//
			// satEnd_dateTimePicker
			//
			this.satEnd_dateTimePicker = new System.Windows.Forms.DateTimePicker();
			this.satEnd_dateTimePicker.CustomFormat = "dd/MM/yyyy, hh:mm"; 
			this.satEnd_dateTimePicker.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.satEnd_dateTimePicker.Location = new System.Drawing.Point(440, 284);
			this.satEnd_dateTimePicker.Name = "satEnd_dateTimePicker";
			this.satEnd_dateTimePicker.Size = new System.Drawing.Size(200, 20);
			this.satEnd_dateTimePicker.TabIndex = 38;
			this.satEnd_dateTimePicker.Value = new System.DateTime(2014, 5, 26, 17, 35, 11, 0);
			this.Panel1.Controls.Add( this.satEnd_dateTimePicker );
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel4.Location = new System.Drawing.Point(656, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(10, 183);
			this.panel4.TabIndex = 3;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.Panel1);
			this.panel3.Controls.Add(this.panel4);
			this.panel3.Controls.Add(this.panel5);
			this.panel3.Controls.Add(this.panel6);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel3.Location = new System.Drawing.Point(0, 25);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(666, 183);
			this.panel3.TabIndex = 19;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel5.Location = new System.Drawing.Point(0, 0);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(10, 183);
			this.panel5.TabIndex = 5;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.panel6.Location = new System.Drawing.Point(0, 324);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(400, 10);
			this.panel6.TabIndex = 6;
			
			
			// 
			// frmemployee
			// 
			this.AutoScroll = true;
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(400, 359);
			this.Name = "frmemployee";
			this.Text = "frmemployee";
			this.Load += new System.EventHandler(this.frmemployee_Load);
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmemployee_FormClosing);
			((System.ComponentModel.ISupportInitialize)(this.bindingNavigator1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
			this.bindingNavigator1.ResumeLayout(false);
			this.bindingNavigator1.PerformLayout();
			this.Text = "Employee";
			((System.ComponentModel.ISupportInitialize)(this.employeeBindingSource)).EndInit();
			this.Controls.Add(this.panel3);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			
			this.Controls.Add(this.bindingNavigator1);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
			
		}
		
		#endregion
		
		private System.Windows.Forms.BindingNavigator bindingNavigator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorAddNewItem;
		private System.Windows.Forms.ToolStripLabel bindingNavigatorCountItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorDeleteItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveFirstItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMovePreviousItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator;
		private System.Windows.Forms.ToolStripTextBox bindingNavigatorPositionItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator1;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveNextItem;
		private System.Windows.Forms.ToolStripButton bindingNavigatorMoveLastItem;
		private System.Windows.Forms.ToolStripSeparator bindingNavigatorSeparator2;
		private System.Windows.Forms.ToolStripButton toolStripButton1;
		private System.Windows.Forms.ErrorProvider errorProvider1;
		private System.Windows.Forms.Panel Panel1;
		private System.Windows.Forms.BindingSource employeeBindingSource;
		private System.Windows.Forms.TextBox employeeIDTextBox;
		private System.Windows.Forms.Label employeeIDLabel;
		private System.Windows.Forms.TextBox passwordTextBox;
		private System.Windows.Forms.Label passwordLabel;
		private System.Windows.Forms.TextBox firstNameTextBox;
		private System.Windows.Forms.Label firstNameLabel;
		private System.Windows.Forms.TextBox lastNameTextBox;
		private System.Windows.Forms.Label lastNameLabel;
		private System.Windows.Forms.ComboBox access_levelID_comboBox;
		private System.Windows.Forms.Label access_levelIDLabel;
		private System.Windows.Forms.DateTimePicker sunStart_dateTimePicker;
		private System.Windows.Forms.Label sunStartLabel;
		private System.Windows.Forms.DateTimePicker sunEnd_dateTimePicker;
		private System.Windows.Forms.Label sunEndLabel;
		private System.Windows.Forms.DateTimePicker monStart_dateTimePicker;
		private System.Windows.Forms.Label monStartLabel;
		private System.Windows.Forms.DateTimePicker monEnd_dateTimePicker;
		private System.Windows.Forms.Label monEndLabel;
		private System.Windows.Forms.DateTimePicker tueStart_dateTimePicker;
		private System.Windows.Forms.Label tueStartLabel;
		private System.Windows.Forms.DateTimePicker tueEnd_dateTimePicker;
		private System.Windows.Forms.Label tueEndLabel;
		private System.Windows.Forms.DateTimePicker wedStart_dateTimePicker;
		private System.Windows.Forms.Label wedStartLabel;
		private System.Windows.Forms.DateTimePicker wedEnd_dateTimePicker;
		private System.Windows.Forms.Label wedEndLabel;
		private System.Windows.Forms.DateTimePicker thuStart_dateTimePicker;
		private System.Windows.Forms.Label thuStartLabel;
		private System.Windows.Forms.DateTimePicker thuEnd_dateTimePicker;
		private System.Windows.Forms.Label thuEndLabel;
		private System.Windows.Forms.DateTimePicker friStart_dateTimePicker;
		private System.Windows.Forms.Label friStartLabel;
		private System.Windows.Forms.DateTimePicker friEnd_dateTimePicker;
		private System.Windows.Forms.Label friEndLabel;
		private System.Windows.Forms.DateTimePicker satStart_dateTimePicker;
		private System.Windows.Forms.Label satStartLabel;
		private System.Windows.Forms.DateTimePicker satEnd_dateTimePicker;
		private System.Windows.Forms.Label satEndLabel;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel4;
		private System.Windows.Forms.Panel panel5;
		private System.Windows.Forms.Panel panel6;
		
	}
}

