/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Objects;

namespace ppSoft_MySql
{
	public partial class frmemployee : Form
	{
		private Model1Entities ctx;
		
		public frmemployee()
		{
			InitializeComponent();
		}
		
		private void frmemployee_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ObjectResult<employee> _entities = ctx.employee.Execute(MergeOption.AppendOnly);
			employeeBindingSource.DataSource = _entities;
			this.employeeIDTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "employeeID", true ));
			this.passwordTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "password", true ));
			this.firstNameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "firstName", true ));
			this.lastNameTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "lastName", true ));
			this.access_levelID_comboBox.DataSource = ctx.access_level.ToList();
			this.access_levelID_comboBox.DisplayMember = "access_levelID";
			this.access_levelID_comboBox.ValueMember = "access_levelID";
			this.access_levelID_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.employeeBindingSource, "access_levelID", true));
			this.sunStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "sunStart", true ));
			this.sunEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "sunEnd", true ));
			this.monStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "monStart", true ));
			this.monEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "monEnd", true ));
			this.tueStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "tueStart", true ));
			this.tueEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "tueEnd", true ));
			this.wedStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "wedStart", true ));
			this.wedEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "wedEnd", true ));
			this.thuStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "thuStart", true ));
			this.thuEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "thuEnd", true ));
			this.friStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "friStart", true ));
			this.friEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "friEnd", true ));
			this.satStart_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "satStart", true ));
			this.satEnd_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.employeeBindingSource, "satEnd", true ));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			employeeBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmemployee_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void employeeIDTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( employeeIDTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( employeeIDTextBox, "The field employeeID is required" ); 
			}
			int v;
			string s = employeeIDTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( employeeIDTextBox, "The field employeeID must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( employeeIDTextBox, "" ); } 
		}
		
		private void passwordTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( passwordTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( passwordTextBox, "The field password is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( passwordTextBox, "" ); } 
		}
		
		private void firstNameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( firstNameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( firstNameTextBox, "The field firstName is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( firstNameTextBox, "" ); } 
		}
		
		private void lastNameTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( lastNameTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( lastNameTextBox, "The field lastName is required" ); 
			}
			if( !e.Cancel ) { errorProvider1.SetError( lastNameTextBox, "" ); } 
		}
		
		private void access_levelID_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = access_levelID_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(access_levelID_comboBox, "Must select a access_levelID");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(access_levelID_comboBox, "");
			}
		}
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			employeeBindingSource.AddNew();
		}
	}
}
