/*
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * This code is generated by a tool and is provided "as is", without warranty of any kind,
 * express or implied, including but not limited to the warranties of merchantability,
 * fitness for a particular purpose and non-infringement.
 * In no event shall the authors or copyright holders be liable for any claim, damages or
 * other liability, whether in an action of contract, tort or otherwise, arising from,
 * out of or in connection with the software or the use or other dealings in the software.
 * ++++++++++++++++++++++++++++++++++++++++++++++++++
 * */

namespace ppSoft_MySql
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.formsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmaccess_levelToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmdepartmentToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmemployeeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
      this.frmshiftToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();

            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(284, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";

      this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.formsToolStripMenuItem });
      // 
      // formsToolStripMenuItem
      // 
      this.formsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { 
      this.frmaccess_levelToolStripMenuItem ,       this.frmdepartmentToolStripMenuItem ,       this.frmemployeeToolStripMenuItem ,       this.frmshiftToolStripMenuItem       });
      this.formsToolStripMenuItem.Name = "formsToolStripMenuItem";
      this.formsToolStripMenuItem.Size = new System.Drawing.Size(52, 20);
      this.formsToolStripMenuItem.Text = "Forms"; 
      // 
      // frmaccess_levelToolStripMenuItem
      // 
      this.frmaccess_levelToolStripMenuItem.Name = "frmaccess_levelToolStripMenuItem";
      this.frmaccess_levelToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmaccess_levelToolStripMenuItem.Text = "access_level";
      this.frmaccess_levelToolStripMenuItem.Click += new System.EventHandler(this.frmaccess_levelToolStripMenuItem_Click);
      // 
      // frmdepartmentToolStripMenuItem
      // 
      this.frmdepartmentToolStripMenuItem.Name = "frmdepartmentToolStripMenuItem";
      this.frmdepartmentToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmdepartmentToolStripMenuItem.Text = "department";
      this.frmdepartmentToolStripMenuItem.Click += new System.EventHandler(this.frmdepartmentToolStripMenuItem_Click);
      // 
      // frmemployeeToolStripMenuItem
      // 
      this.frmemployeeToolStripMenuItem.Name = "frmemployeeToolStripMenuItem";
      this.frmemployeeToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmemployeeToolStripMenuItem.Text = "employee";
      this.frmemployeeToolStripMenuItem.Click += new System.EventHandler(this.frmemployeeToolStripMenuItem_Click);
      // 
      // frmshiftToolStripMenuItem
      // 
      this.frmshiftToolStripMenuItem.Name = "frmshiftToolStripMenuItem";
      this.frmshiftToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
      this.frmshiftToolStripMenuItem.Text = "shift";
      this.frmshiftToolStripMenuItem.Click += new System.EventHandler(this.frmshiftToolStripMenuItem_Click);

            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 261);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "frmMain";
            this.Text = "Main Form";
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem formsToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmaccess_levelToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmdepartmentToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmemployeeToolStripMenuItem;
    private System.Windows.Forms.ToolStripMenuItem frmshiftToolStripMenuItem;

    }
}
