/*
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* This code is generated by a tool and is provided "as is", without warranty of any kind,
* express or implied, including but not limited to the warranties of merchantability,
* fitness for a particular purpose and non-infringement.
* In no event shall the authors or copyright holders be liable for any claim, damages or
* other liability, whether in an action of contract, tort or otherwise, arising from,
* out of or in connection with the software or the use or other dealings in the software.
* ++++++++++++++++++++++++++++++++++++++++++++++++++
* */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using MySql.Data.MySqlClient;
using System.Data.Objects;

namespace ppSoft_MySql
{
	public partial class frmshift : Form
	{
		private Model1Entities ctx;
		
		public frmshift()
		{
			InitializeComponent();
		}
		
		private void frmshift_Load(object sender, EventArgs e)
		{
			ctx = new Model1Entities();
			ObjectResult<shift> _entities = ctx.shift.Execute(MergeOption.AppendOnly);
			shiftBindingSource.DataSource = _entities;
			this.shiftIDTextBox.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shiftBindingSource, "shiftID", true ));
			this.employeeID_comboBox.DataSource = ctx.employee.ToList();
			this.employeeID_comboBox.DisplayMember = "employeeID";
			this.employeeID_comboBox.ValueMember = "employeeID";
			this.employeeID_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.shiftBindingSource, "employeeID", true));
			this.start_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shiftBindingSource, "start", true ));
			this.finish_dateTimePicker.DataBindings.Add(new System.Windows.Forms.Binding("Text", this.shiftBindingSource, "finish", true ));
			this.departmentID_comboBox.DataSource = ctx.department.ToList();
			this.departmentID_comboBox.DisplayMember = "departmentID";
			this.departmentID_comboBox.ValueMember = "departmentID";
			this.departmentID_comboBox.DataBindings.Add(new System.Windows.Forms.Binding("SelectedValue", this.shiftBindingSource, "departmentID", true));
			
		}
		
		private void Save_Click(object sender, EventArgs e)
		{
			if (!this.Validate()) return;
			shiftBindingSource.EndEdit();
			ctx.SaveChanges();
			
		}
		
		private void frmshift_FormClosing(object sender, FormClosingEventArgs e)
		{
			e.Cancel = false;
		}
		
		private void shiftIDTextBox_Validating(object sender, CancelEventArgs e)
		{
			e.Cancel = false;
			if( string.IsNullOrEmpty( shiftIDTextBox.Text ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( shiftIDTextBox, "The field shiftID is required" ); 
			}
			int v;
			string s = shiftIDTextBox.Text;
			if( !int.TryParse( s, out v ) )
			{
				e.Cancel = true;
				errorProvider1.SetError( shiftIDTextBox, "The field shiftID must be int." );
			}
			if( !e.Cancel ) { errorProvider1.SetError( shiftIDTextBox, "" ); } 
		}
		
		private void employeeID_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = employeeID_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(employeeID_comboBox, "Must select a employeeID");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(employeeID_comboBox, "");
			}
		}
		private void departmentID_comboBox_Validating(object sender, CancelEventArgs e)
		{
			int i = departmentID_comboBox.SelectedIndex;
			e.Cancel = false;
			if( i == -1 )
			{
				e.Cancel = true; 
				errorProvider1.SetError(departmentID_comboBox, "Must select a departmentID");
			}
			if( !e.Cancel )
			{
				errorProvider1.SetError(departmentID_comboBox, "");
			}
		}
		
		
		
		private void bindingNavigatorAddNewItem_Click(object sender, EventArgs e)
		{
			shiftBindingSource.AddNew();
		}
	}
}
