//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ppSoft_MySql", "accessLevelId", "access_level", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ppSoft_MySql.access_level), "employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ppSoft_MySql.employee), true)]
[assembly: EdmRelationshipAttribute("ppSoft_MySql", "departmentID", "department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ppSoft_MySql.department), "shift", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ppSoft_MySql.shift), true)]
[assembly: EdmRelationshipAttribute("ppSoft_MySql", "employeeID", "employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ppSoft_MySql.employee), "shift", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ppSoft_MySql.shift), true)]

#endregion

namespace ppSoft_MySql
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Entities object using the connection string found in the 'Model1Entities' section of the application configuration file.
        /// </summary>
        public Model1Entities() : base("name=Model1Entities", "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Entities object.
        /// </summary>
        public Model1Entities(string connectionString) : base(connectionString, "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Entities object.
        /// </summary>
        public Model1Entities(EntityConnection connection) : base(connection, "Model1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<access_level> access_level
        {
            get
            {
                if ((_access_level == null))
                {
                    _access_level = base.CreateObjectSet<access_level>("access_level");
                }
                return _access_level;
            }
        }
        private ObjectSet<access_level> _access_level;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<department> department
        {
            get
            {
                if ((_department == null))
                {
                    _department = base.CreateObjectSet<department>("department");
                }
                return _department;
            }
        }
        private ObjectSet<department> _department;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee> employee
        {
            get
            {
                if ((_employee == null))
                {
                    _employee = base.CreateObjectSet<employee>("employee");
                }
                return _employee;
            }
        }
        private ObjectSet<employee> _employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<shift> shift
        {
            get
            {
                if ((_shift == null))
                {
                    _shift = base.CreateObjectSet<shift>("shift");
                }
                return _shift;
            }
        }
        private ObjectSet<shift> _shift;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the access_level EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccess_level(access_level access_level)
        {
            base.AddObject("access_level", access_level);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the department EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodepartment(department department)
        {
            base.AddObject("department", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployee(employee employee)
        {
            base.AddObject("employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the shift EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToshift(shift shift)
        {
            base.AddObject("shift", shift);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ppSoft_MySql", Name="access_level")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class access_level : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new access_level object.
        /// </summary>
        /// <param name="access_levelID">Initial value of the access_levelID property.</param>
        /// <param name="access">Initial value of the access property.</param>
        public static access_level Createaccess_level(global::System.Int32 access_levelID, global::System.String access)
        {
            access_level access_level = new access_level();
            access_level.access_levelID = access_levelID;
            access_level.access = access;
            return access_level;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 access_levelID
        {
            get
            {
                return _access_levelID;
            }
            set
            {
                if (_access_levelID != value)
                {
                    Onaccess_levelIDChanging(value);
                    ReportPropertyChanging("access_levelID");
                    _access_levelID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("access_levelID");
                    Onaccess_levelIDChanged();
                }
            }
        }
        private global::System.Int32 _access_levelID;
        partial void Onaccess_levelIDChanging(global::System.Int32 value);
        partial void Onaccess_levelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String access
        {
            get
            {
                return _access;
            }
            set
            {
                OnaccessChanging(value);
                ReportPropertyChanging("access");
                _access = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("access");
                OnaccessChanged();
            }
        }
        private global::System.String _access;
        partial void OnaccessChanging(global::System.String value);
        partial void OnaccessChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "accessLevelId", "employee")]
        public EntityCollection<employee> employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<employee>("ppSoft_MySql.accessLevelId", "employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<employee>("ppSoft_MySql.accessLevelId", "employee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ppSoft_MySql", Name="department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new department object.
        /// </summary>
        /// <param name="departmentID">Initial value of the departmentID property.</param>
        /// <param name="department1">Initial value of the department1 property.</param>
        public static department Createdepartment(global::System.Int32 departmentID, global::System.String department1)
        {
            department department = new department();
            department.departmentID = departmentID;
            department.department1 = department1;
            return department;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 departmentID
        {
            get
            {
                return _departmentID;
            }
            set
            {
                if (_departmentID != value)
                {
                    OndepartmentIDChanging(value);
                    ReportPropertyChanging("departmentID");
                    _departmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("departmentID");
                    OndepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _departmentID;
        partial void OndepartmentIDChanging(global::System.Int32 value);
        partial void OndepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String department1
        {
            get
            {
                return _department1;
            }
            set
            {
                Ondepartment1Changing(value);
                ReportPropertyChanging("department1");
                _department1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("department1");
                Ondepartment1Changed();
            }
        }
        private global::System.String _department1;
        partial void Ondepartment1Changing(global::System.String value);
        partial void Ondepartment1Changed();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "departmentID", "shift")]
        public EntityCollection<shift> shift
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<shift>("ppSoft_MySql.departmentID", "shift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<shift>("ppSoft_MySql.departmentID", "shift", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ppSoft_MySql", Name="employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the employeeID property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="access_levelID">Initial value of the access_levelID property.</param>
        public static employee Createemployee(global::System.Int32 employeeID, global::System.String password, global::System.String firstName, global::System.String lastName, global::System.Int32 access_levelID)
        {
            employee employee = new employee();
            employee.employeeID = employeeID;
            employee.password = password;
            employee.firstName = firstName;
            employee.lastName = lastName;
            employee.access_levelID = access_levelID;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employeeID
        {
            get
            {
                return _employeeID;
            }
            set
            {
                if (_employeeID != value)
                {
                    OnemployeeIDChanging(value);
                    ReportPropertyChanging("employeeID");
                    _employeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("employeeID");
                    OnemployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _employeeID;
        partial void OnemployeeIDChanging(global::System.Int32 value);
        partial void OnemployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 access_levelID
        {
            get
            {
                return _access_levelID;
            }
            set
            {
                Onaccess_levelIDChanging(value);
                ReportPropertyChanging("access_levelID");
                _access_levelID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("access_levelID");
                Onaccess_levelIDChanged();
            }
        }
        private global::System.Int32 _access_levelID;
        partial void Onaccess_levelIDChanging(global::System.Int32 value);
        partial void Onaccess_levelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> sunStart
        {
            get
            {
                return _sunStart;
            }
            set
            {
                OnsunStartChanging(value);
                ReportPropertyChanging("sunStart");
                _sunStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sunStart");
                OnsunStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _sunStart;
        partial void OnsunStartChanging(Nullable<global::System.DateTime> value);
        partial void OnsunStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> sunEnd
        {
            get
            {
                return _sunEnd;
            }
            set
            {
                OnsunEndChanging(value);
                ReportPropertyChanging("sunEnd");
                _sunEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sunEnd");
                OnsunEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _sunEnd;
        partial void OnsunEndChanging(Nullable<global::System.DateTime> value);
        partial void OnsunEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> monStart
        {
            get
            {
                return _monStart;
            }
            set
            {
                OnmonStartChanging(value);
                ReportPropertyChanging("monStart");
                _monStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monStart");
                OnmonStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _monStart;
        partial void OnmonStartChanging(Nullable<global::System.DateTime> value);
        partial void OnmonStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> monEnd
        {
            get
            {
                return _monEnd;
            }
            set
            {
                OnmonEndChanging(value);
                ReportPropertyChanging("monEnd");
                _monEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("monEnd");
                OnmonEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _monEnd;
        partial void OnmonEndChanging(Nullable<global::System.DateTime> value);
        partial void OnmonEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tueStart
        {
            get
            {
                return _tueStart;
            }
            set
            {
                OntueStartChanging(value);
                ReportPropertyChanging("tueStart");
                _tueStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tueStart");
                OntueStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _tueStart;
        partial void OntueStartChanging(Nullable<global::System.DateTime> value);
        partial void OntueStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tueEnd
        {
            get
            {
                return _tueEnd;
            }
            set
            {
                OntueEndChanging(value);
                ReportPropertyChanging("tueEnd");
                _tueEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tueEnd");
                OntueEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _tueEnd;
        partial void OntueEndChanging(Nullable<global::System.DateTime> value);
        partial void OntueEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> wedStart
        {
            get
            {
                return _wedStart;
            }
            set
            {
                OnwedStartChanging(value);
                ReportPropertyChanging("wedStart");
                _wedStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wedStart");
                OnwedStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _wedStart;
        partial void OnwedStartChanging(Nullable<global::System.DateTime> value);
        partial void OnwedStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> wedEnd
        {
            get
            {
                return _wedEnd;
            }
            set
            {
                OnwedEndChanging(value);
                ReportPropertyChanging("wedEnd");
                _wedEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wedEnd");
                OnwedEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _wedEnd;
        partial void OnwedEndChanging(Nullable<global::System.DateTime> value);
        partial void OnwedEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> thuStart
        {
            get
            {
                return _thuStart;
            }
            set
            {
                OnthuStartChanging(value);
                ReportPropertyChanging("thuStart");
                _thuStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("thuStart");
                OnthuStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _thuStart;
        partial void OnthuStartChanging(Nullable<global::System.DateTime> value);
        partial void OnthuStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> thuEnd
        {
            get
            {
                return _thuEnd;
            }
            set
            {
                OnthuEndChanging(value);
                ReportPropertyChanging("thuEnd");
                _thuEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("thuEnd");
                OnthuEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _thuEnd;
        partial void OnthuEndChanging(Nullable<global::System.DateTime> value);
        partial void OnthuEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> friStart
        {
            get
            {
                return _friStart;
            }
            set
            {
                OnfriStartChanging(value);
                ReportPropertyChanging("friStart");
                _friStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("friStart");
                OnfriStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _friStart;
        partial void OnfriStartChanging(Nullable<global::System.DateTime> value);
        partial void OnfriStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> friEnd
        {
            get
            {
                return _friEnd;
            }
            set
            {
                OnfriEndChanging(value);
                ReportPropertyChanging("friEnd");
                _friEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("friEnd");
                OnfriEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _friEnd;
        partial void OnfriEndChanging(Nullable<global::System.DateTime> value);
        partial void OnfriEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> satStart
        {
            get
            {
                return _satStart;
            }
            set
            {
                OnsatStartChanging(value);
                ReportPropertyChanging("satStart");
                _satStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("satStart");
                OnsatStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _satStart;
        partial void OnsatStartChanging(Nullable<global::System.DateTime> value);
        partial void OnsatStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> satEnd
        {
            get
            {
                return _satEnd;
            }
            set
            {
                OnsatEndChanging(value);
                ReportPropertyChanging("satEnd");
                _satEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("satEnd");
                OnsatEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _satEnd;
        partial void OnsatEndChanging(Nullable<global::System.DateTime> value);
        partial void OnsatEndChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "accessLevelId", "access_level")]
        public access_level access_level
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_level>("ppSoft_MySql.accessLevelId", "access_level").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_level>("ppSoft_MySql.accessLevelId", "access_level").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<access_level> access_levelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_level>("ppSoft_MySql.accessLevelId", "access_level");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<access_level>("ppSoft_MySql.accessLevelId", "access_level", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "employeeID", "shift")]
        public EntityCollection<shift> shift
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<shift>("ppSoft_MySql.employeeID", "shift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<shift>("ppSoft_MySql.employeeID", "shift", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ppSoft_MySql", Name="shift")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class shift : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new shift object.
        /// </summary>
        /// <param name="shiftID">Initial value of the shiftID property.</param>
        /// <param name="employeeID">Initial value of the employeeID property.</param>
        /// <param name="start">Initial value of the start property.</param>
        /// <param name="finish">Initial value of the finish property.</param>
        /// <param name="departmentID">Initial value of the departmentID property.</param>
        public static shift Createshift(global::System.Int32 shiftID, global::System.Int32 employeeID, global::System.DateTime start, global::System.DateTime finish, global::System.Int32 departmentID)
        {
            shift shift = new shift();
            shift.shiftID = shiftID;
            shift.employeeID = employeeID;
            shift.start = start;
            shift.finish = finish;
            shift.departmentID = departmentID;
            return shift;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 shiftID
        {
            get
            {
                return _shiftID;
            }
            set
            {
                if (_shiftID != value)
                {
                    OnshiftIDChanging(value);
                    ReportPropertyChanging("shiftID");
                    _shiftID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("shiftID");
                    OnshiftIDChanged();
                }
            }
        }
        private global::System.Int32 _shiftID;
        partial void OnshiftIDChanging(global::System.Int32 value);
        partial void OnshiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employeeID
        {
            get
            {
                return _employeeID;
            }
            set
            {
                OnemployeeIDChanging(value);
                ReportPropertyChanging("employeeID");
                _employeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("employeeID");
                OnemployeeIDChanged();
            }
        }
        private global::System.Int32 _employeeID;
        partial void OnemployeeIDChanging(global::System.Int32 value);
        partial void OnemployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime start
        {
            get
            {
                return _start;
            }
            set
            {
                OnstartChanging(value);
                ReportPropertyChanging("start");
                _start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start");
                OnstartChanged();
            }
        }
        private global::System.DateTime _start;
        partial void OnstartChanging(global::System.DateTime value);
        partial void OnstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime finish
        {
            get
            {
                return _finish;
            }
            set
            {
                OnfinishChanging(value);
                ReportPropertyChanging("finish");
                _finish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("finish");
                OnfinishChanged();
            }
        }
        private global::System.DateTime _finish;
        partial void OnfinishChanging(global::System.DateTime value);
        partial void OnfinishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 departmentID
        {
            get
            {
                return _departmentID;
            }
            set
            {
                OndepartmentIDChanging(value);
                ReportPropertyChanging("departmentID");
                _departmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("departmentID");
                OndepartmentIDChanged();
            }
        }
        private global::System.Int32 _departmentID;
        partial void OndepartmentIDChanging(global::System.Int32 value);
        partial void OndepartmentIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "departmentID", "department")]
        public department department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("ppSoft_MySql.departmentID", "department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("ppSoft_MySql.departmentID", "department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<department> departmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<department>("ppSoft_MySql.departmentID", "department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<department>("ppSoft_MySql.departmentID", "department", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ppSoft_MySql", "employeeID", "employee")]
        public employee employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("ppSoft_MySql.employeeID", "employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("ppSoft_MySql.employeeID", "employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<employee> employeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<employee>("ppSoft_MySql.employeeID", "employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<employee>("ppSoft_MySql.employeeID", "employee", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
