//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSoft_SkedgeITModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.shifts = new HashSet<shift>();
        }
    
        public int employeeID { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int access_levelID { get; set; }
        public Nullable<System.TimeSpan> sunStart { get; set; }
        public Nullable<System.TimeSpan> sunEnd { get; set; }
        public Nullable<System.TimeSpan> monStart { get; set; }
        public Nullable<System.TimeSpan> monEnd { get; set; }
        public Nullable<System.TimeSpan> tueStart { get; set; }
        public Nullable<System.TimeSpan> tueEnd { get; set; }
        public Nullable<System.TimeSpan> wedStart { get; set; }
        public Nullable<System.TimeSpan> wedEnd { get; set; }
        public Nullable<System.TimeSpan> thuStart { get; set; }
        public Nullable<System.TimeSpan> thuEnd { get; set; }
        public Nullable<System.TimeSpan> friStart { get; set; }
        public Nullable<System.TimeSpan> friEnd { get; set; }
        public Nullable<System.TimeSpan> satStart { get; set; }
        public Nullable<System.TimeSpan> satEnd { get; set; }
    
        public virtual access_level access_level { get; set; }
        public virtual ICollection<shift> shifts { get; set; }
    }
}
