//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSoft_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class access_level
    {
        public access_level()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int access_levelID { get; set; }
        public string access { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
