//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPSoft_DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int shiftID { get; set; }
        public int employeeID { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime finish { get; set; }
        public int departmentID { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
    }
}
